CREATE TABLE `customers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerCode` varchar(40) NOT NULL,
	`name` varchar(255) NOT NULL,
	`commercialRegister` varchar(100) NOT NULL,
	`taxNumber` varchar(100),
	`isTaxRegistered` int NOT NULL DEFAULT 0,
	`municipalLicense` varchar(100),
	`nationalAddress` text NOT NULL,
	`city` varchar(100) NOT NULL,
	`district` varchar(100) NOT NULL,
	`street` varchar(150) NOT NULL,
	`email` varchar(320) NOT NULL,
	`ownerName` varchar(255) NOT NULL,
	`ownerPhone` varchar(30) NOT NULL,
	`contactName` varchar(255) NOT NULL,
	`contactPhone` varchar(30) NOT NULL,
	`contactEmail` varchar(320),
	`latitude` decimal(10,7) NOT NULL,
	`longitude` decimal(10,7) NOT NULL,
	`attachments` json NOT NULL,
	`version` int NOT NULL DEFAULT 1,
	`isActive` int NOT NULL DEFAULT 1,
	`createdBy` int NOT NULL,
	`updatedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customers_id` PRIMARY KEY(`id`),
	CONSTRAINT `customers_customerCode_unique` UNIQUE(`customerCode`)
);
--> statement-breakpoint
CREATE TABLE `representativeAttachments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int,
	`transactionId` int,
	`attachmentType` varchar(80) NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileUrl` text NOT NULL,
	`mimeType` varchar(120),
	`expiresAt` varchar(20),
	`version` int NOT NULL DEFAULT 1,
	`isActive` int NOT NULL DEFAULT 1,
	`uploadedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `representativeAttachments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `representativeCollections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`referenceCode` varchar(40) NOT NULL,
	`representativeId` int NOT NULL,
	`representativeName` varchar(255) NOT NULL,
	`customerId` int NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`transactionId` int,
	`invoiceNumber` varchar(100),
	`invoiceAmount` decimal(14,2) DEFAULT 0,
	`collectedAmount` decimal(14,2) NOT NULL,
	`remainingAmount` decimal(14,2) DEFAULT 0,
	`collectionMethod` enum('cash','transfer') NOT NULL,
	`receiptNumber` varchar(100),
	`collectionDate` varchar(20) NOT NULL,
	`notes` text,
	`attachments` json NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `representativeCollections_id` PRIMARY KEY(`id`),
	CONSTRAINT `representativeCollections_referenceCode_unique` UNIQUE(`referenceCode`)
);
--> statement-breakpoint
CREATE TABLE `representativeDeclarations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`transactionId` int NOT NULL,
	`declarationType` varchar(80) NOT NULL,
	`declarationText` text NOT NULL,
	`declarerName` varchar(255) NOT NULL,
	`declarerRole` varchar(100) NOT NULL,
	`signerUserId` int,
	`signatureData` text NOT NULL,
	`signatureAttachmentUrl` text,
	`signedSnapshot` json NOT NULL,
	`signedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `representativeDeclarations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `representativePerformanceWeights` (
	`id` int AUTO_INCREMENT NOT NULL,
	`criterionKey` varchar(80) NOT NULL,
	`criterionName` varchar(255) NOT NULL,
	`weight` int NOT NULL,
	`targetValue` decimal(14,2) DEFAULT 0,
	`isActive` int NOT NULL DEFAULT 1,
	`updatedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `representativePerformanceWeights_id` PRIMARY KEY(`id`),
	CONSTRAINT `representativePerformanceWeights_criterionKey_unique` UNIQUE(`criterionKey`)
);
--> statement-breakpoint
CREATE TABLE `representativeTransactionItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`transactionId` int NOT NULL,
	`productName` varchar(255) NOT NULL,
	`size` varchar(100) NOT NULL,
	`color` varchar(100) NOT NULL,
	`quantity` int NOT NULL,
	`quantityUnit` enum('dozen','pair') NOT NULL,
	`productType` varchar(100),
	`yarnRatios` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `representativeTransactionItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `representativeTransactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`referenceCode` varchar(40) NOT NULL,
	`transactionType` enum('order','visit','return','custom','sample') NOT NULL,
	`representativeId` int NOT NULL,
	`representativeName` varchar(255) NOT NULL,
	`customerId` int NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`customerVersion` int NOT NULL DEFAULT 1,
	`status` varchar(80) NOT NULL DEFAULT 'DRAFT',
	`currentDepartment` varchar(100) NOT NULL DEFAULT 'sales_representative',
	`currentAssigneeId` int,
	`currentAssigneeName` varchar(255),
	`orderDate` varchar(20),
	`deliveryDate` varchar(20),
	`paymentMethod` enum('cash','transfer','credit'),
	`paymentAmount` decimal(14,2) DEFAULT 0,
	`receiptNumber` varchar(100),
	`receiptDate` varchar(20),
	`creditDays` int,
	`visitReport` text,
	`productData` json NOT NULL,
	`yarnRatios` json,
	`attachments` json NOT NULL,
	`signedSnapshot` json,
	`invoiceNumber` varchar(100),
	`invoiceAttachments` json,
	`rejectionReason` text,
	`correctiveAction` json,
	`submittedAt` timestamp,
	`closedAt` timestamp,
	`deletedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `representativeTransactions_id` PRIMARY KEY(`id`),
	CONSTRAINT `representativeTransactions_referenceCode_unique` UNIQUE(`referenceCode`)
);
--> statement-breakpoint
CREATE TABLE `representativeWorkflowEvents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`transactionId` int NOT NULL,
	`fromStatus` varchar(80),
	`toStatus` varchar(80) NOT NULL,
	`action` varchar(100) NOT NULL,
	`actorId` int NOT NULL,
	`actorName` varchar(255) NOT NULL,
	`actorDepartment` varchar(100),
	`notes` text,
	`attachments` json,
	`previousEventAt` timestamp,
	`durationMinutes` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `representativeWorkflowEvents_id` PRIMARY KEY(`id`)
);
