import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { MaterialIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { BackButton } from "@/components/back-button";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { finishedWarehouseService } from "@/lib/services/api.service";

type StockRow = { id: number; productName: string; productSize?: string; productColor?: string; quantityDozen: number; minimumDozen: number; lastMovementAt?: string | Date | null; isLow?: boolean; ageDays?: number | null; activityStatus?: "active" | "stagnant" };

export default function FinishedWarehouseInventoryScreen() {
  const colors = useColors(); const router = useRouter();
  const [rows, setRows] = useState<StockRow[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [lowOnly, setLowOnly] = useState(false); const [stagnantOnly, setStagnantOnly] = useState(false); const [sortKey, setSortKey] = useState<"name" | "quantity" | "age">("name");
  const load = useCallback(async () => { setLoading(true); try { const result: any = query.trim() ? await finishedWarehouseService.search(query.trim()) : await finishedWarehouseService.summary(); setRows((result?.items || result || []) as StockRow[]); } catch (e: any) { Alert.alert("تعذر تحميل المخزون", e?.message || "حدث خطأ"); } finally { setLoading(false); } }, [query]);
  useEffect(() => { const timer = setTimeout(() => void load(), query ? 250 : 0); return () => clearTimeout(timer); }, [load, query]);
  const visibleRows = useMemo(() => rows.filter((row) => (!lowOnly || Number(row.quantityDozen) < Number(row.minimumDozen)) && (!stagnantOnly || row.activityStatus === "stagnant")), [rows, lowOnly, stagnantOnly]);
  const sortedRows = useMemo(() => [...visibleRows].sort((a, b) => sortKey === "quantity" ? Number(b.quantityDozen) - Number(a.quantityDozen) : sortKey === "age" ? Number(b.ageDays || 0) - Number(a.ageDays || 0) : String(a.productName).localeCompare(String(b.productName), "ar")), [visibleRows, sortKey]);
  const total = sortedRows.reduce((sum, row) => sum + Number(row.quantityDozen || 0), 0); const lowCount = rows.filter((row) => Number(row.quantityDozen) < Number(row.minimumDozen || 50)).length; const stagnantCount = rows.filter((row) => row.activityStatus === "stagnant").length; const activePercent = rows.length ? Math.round(((rows.length - stagnantCount) / rows.length) * 100) : 0; const stagnantPercent = rows.length ? Math.round((stagnantCount / rows.length) * 100) : 0;
  return <ScreenContainer style={{ backgroundColor: colors.background }}>
    <View style={styles.header}><View><Text style={styles.title}>مستودع الإنتاج التام</Text><Text style={styles.subtitle}>رصيد التخزين بالدرزن — يتحدث تلقائياً عند استلام مرحلة التخزين</Text></View><BackButton /></View>
    <ScrollView contentContainerStyle={styles.content}>
      <View style={styles.stats}><Stat label="إجمالي الأصناف" value={String(rows.length)} color="#0a7ea4" /><Stat label="إجمالي الرصيد (درزن)" value={String(total)} color="#16a34a" /><Stat label="تحت حد 50 درزن" value={String(lowCount)} color="#dc2626" /><Stat label="نشاط المنتجات" value={`${activePercent}%`} color="#16a34a" /><Stat label="ركود المنتجات" value={`${stagnantPercent}%`} color="#d97706" /></View>
      <View style={styles.toolbar}><TextInput value={query} onChangeText={setQuery} placeholder="اكتب اسم المنتج أو المقاس أو اللون للبحث فقط" placeholderTextColor="#94a3b8" style={styles.search} textAlign="right" /><TouchableOpacity onPress={() => router.push("/product-manufacturing-request")} style={styles.requestButton}><MaterialIcons name="add-task" size={18} color="white" /><Text style={styles.buttonText}>طلب تصنيع منتج</Text></TouchableOpacity></View>
      <View style={styles.filters}><Filter label="الأصناف تحت الحد" active={lowOnly} onPress={() => setLowOnly(!lowOnly)} /><Filter label="الأصناف الراكدة" active={stagnantOnly} onPress={() => setStagnantOnly(!stagnantOnly)} /></View><View style={styles.filters}><Filter label="ترتيب الاسم" active={sortKey === "name"} onPress={() => setSortKey("name")} /><Filter label="الأعلى رصيداً" active={sortKey === "quantity"} onPress={() => setSortKey("quantity")} /><Filter label="الأقدم حركة" active={sortKey === "age"} onPress={() => setSortKey("age")} /></View><View style={styles.exportBar}><TouchableOpacity onPress={() => exportReport("word", sortedRows)} style={styles.exportWord}><MaterialIcons name="description" size={17} color="white" /><Text style={styles.buttonText}>Word</Text></TouchableOpacity><TouchableOpacity onPress={() => exportReport("excel", sortedRows)} style={styles.exportExcel}><MaterialIcons name="grid-on" size={17} color="white" /><Text style={styles.buttonText}>Excel</Text></TouchableOpacity><TouchableOpacity onPress={() => printReport(sortedRows)} style={styles.exportPrint}><MaterialIcons name="print" size={17} color="white" /><Text style={styles.buttonText}>طباعة</Text></TouchableOpacity></View>
      <View style={styles.note}><MaterialIcons name="info-outline" size={18} color="#92400e" /><Text style={styles.noteText}>الحد الأدنى الافتراضي لكل صنف هو 50 درزناً. عند انخفاض الرصيد يظهر تنبيه لمسؤول المستودعات والأدمن، ولا يسمح النظام بإخراج كمية أكبر من الرصيد الفعلي.</Text></View>
      {loading ? <Text style={styles.empty}>جارٍ تحميل الرصيد...</Text> : sortedRows.length === 0 ? <Text style={styles.empty}>{query ? "لا توجد نتيجة مطابقة للبحث" : "لا توجد أصناف في العرض الحالي"}</Text> : <View style={styles.table}><View style={styles.tableHeader}><Text style={[styles.cell, styles.headerCell, { flex: 2 }]}>اسم المنتج</Text><Text style={[styles.cell, styles.headerCell]}>المقاس</Text><Text style={[styles.cell, styles.headerCell]}>اللون</Text><Text style={[styles.cell, styles.headerCell]}>الرصيد (درزن)</Text><Text style={[styles.cell, styles.headerCell]}>الحالة</Text></View>{sortedRows.map((row) => <View key={row.id} style={[styles.tableRow, Number(row.quantityDozen) < Number(row.minimumDozen || 50) && styles.lowRow]}><Text style={[styles.cell, { flex: 2, fontWeight: "700" }]}>{row.productName}</Text><Text style={styles.cell}>{row.productSize || "-"}</Text><Text style={styles.cell}>{row.productColor || "-"}</Text><Text style={[styles.cell, { color: Number(row.quantityDozen) < Number(row.minimumDozen || 50) ? "#dc2626" : "#166534", fontWeight: "800" }]}>{Number(row.quantityDozen).toLocaleString("ar-SA")}</Text><Text style={[styles.cell, { color: row.activityStatus === "stagnant" ? "#b45309" : "#166534" }]}>{row.activityStatus === "stagnant" ? "راكد" : "نشط"}</Text></View>)}</View>}
    </ScrollView>
  </ScreenContainer>;
}
function exportReport(format: "word" | "excel", rows: StockRow[]) {
  if (Platform.OS !== "web" || typeof document === "undefined") return Alert.alert("التصدير متاح من الويب", "افتح النظام من نسخة الويب للتصدير");
  const esc = (v: unknown) => String(v ?? "").replace(/[&<>\"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#039;" } as Record<string, string>)[c] || c);
  const body = rows.map((r, i) => `<tr><td>${i + 1}</td><td>${esc(r.productName)}</td><td>${esc(r.productSize || "-")}</td><td>${esc(r.productColor || "-")}</td><td>${r.quantityDozen}</td><td>${r.minimumDozen || 50}</td><td>${r.activityStatus === "stagnant" ? "راكد" : "نشط"}</td><td>${r.ageDays ?? "-"}</td></tr>`).join("");
  const html = `<!doctype html><html dir="rtl"><head><meta charset="utf-8"><style>@page{size:A4 landscape;margin:8mm}body{font-family:Arial;color:#17202a}h1{color:#166534}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #9fb5bd;padding:6px;text-align:right}th{background:#166534;color:#fff}tr:nth-child(even){background:#f3f8f4}</style></head><body><h1>تقرير مستودع الإنتاج التام</h1><p>تاريخ التصدير: ${new Date().toLocaleString("ar-SA")}</p><table><thead><tr><th>#</th><th>اسم المنتج</th><th>المقاس</th><th>اللون</th><th>الرصيد بالدرزن</th><th>الحد الأدنى</th><th>الحالة</th><th>أيام منذ آخر حركة</th></tr></thead><tbody>${body || '<tr><td colspan="8">لا توجد بيانات</td></tr>'}</tbody></table></body></html>`;
  const blob = new Blob(["\ufeff", html], { type: format === "word" ? "application/msword" : "application/vnd.ms-excel" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `تقرير-مستودع-الإنتاج-${new Date().toISOString().slice(0, 10)}.${format === "word" ? "doc" : "xls"}`; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
}
function printReport(rows: StockRow[]) {
  if (Platform.OS !== "web" || typeof window === "undefined") return Alert.alert("الطباعة متاحة من الويب", "افتح النظام من نسخة الويب للطباعة");
  const esc = (v: unknown) => String(v ?? "").replace(/[&<>\"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#039;" } as Record<string, string>)[c] || c);
  const body = rows.map((r, i) => `<tr><td>${i + 1}</td><td>${esc(r.productName)}</td><td>${esc(r.productSize || "-")}</td><td>${esc(r.productColor || "-")}</td><td>${r.quantityDozen}</td><td>${r.minimumDozen || 50}</td><td>${r.activityStatus === "stagnant" ? "راكد" : "نشط"}</td><td>${r.ageDays ?? "-"}</td></tr>`).join("");
  const win = window.open("", "_blank", "width=1200,height=800"); if (!win) return; win.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>تقرير مستودع الإنتاج التام</title><style>@page{size:A4 landscape;margin:8mm}body{font-family:Arial;color:#17202a}h1{text-align:right;color:#166534}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #9fb5bd;padding:6px;text-align:right}th{background:#166534;color:#fff}tr:nth-child(even){background:#f3f8f4}@media print{button{display:none}}</style></head><body><h1>تقرير مستودع الإنتاج التام</h1><p>تاريخ ووقت الطباعة: ${new Date().toLocaleString("ar-SA")}</p><table><thead><tr><th>#</th><th>اسم المنتج</th><th>المقاس</th><th>اللون</th><th>الرصيد بالدرزن</th><th>الحد الأدنى</th><th>الحالة</th><th>أيام منذ آخر حركة</th></tr></thead><tbody>${body || '<tr><td colspan="8">لا توجد بيانات</td></tr>'}</tbody></table><script>window.onload=()=>window.print()</script></body></html>`); win.document.close();
}

function Stat({ label, value, color }: { label: string; value: string; color: string }) { return <View style={styles.stat}><Text style={[styles.statValue, { color }]}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
function Filter({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <TouchableOpacity onPress={onPress} style={[styles.filter, active && styles.filterActive]}><MaterialIcons name={active ? "check-box" : "check-box-outline-blank"} size={18} color={active ? "white" : "#475569"} /><Text style={[styles.filterText, active && { color: "white" }]}>{label}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ header: { backgroundColor: "#166534", padding: 18, flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", gap: 12 }, title: { color: "white", fontSize: 20, fontWeight: "800", textAlign: "right" }, subtitle: { color: "#dcfce7", fontSize: 12, marginTop: 4, textAlign: "right" }, content: { padding: 16, gap: 12 }, stats: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 10 }, stat: { flex: 1, minWidth: 150, backgroundColor: "white", borderRadius: 12, borderWidth: 1, borderColor: "#e2e8f0", padding: 14, alignItems: "center" }, statValue: { fontSize: 22, fontWeight: "800" }, statLabel: { color: "#64748b", fontSize: 12, marginTop: 4 }, toolbar: { flexDirection: "row-reverse", alignItems: "center", gap: 10 }, search: { flex: 1, minHeight: 44, backgroundColor: "white", borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 10, paddingHorizontal: 12, color: "#0f172a" }, requestButton: { backgroundColor: "#2563eb", borderRadius: 10, paddingHorizontal: 14, minHeight: 44, flexDirection: "row", alignItems: "center", gap: 6 }, buttonText: { color: "white", fontWeight: "700" }, filters: { flexDirection: "row-reverse", gap: 8, flexWrap: "wrap" }, exportBar: { flexDirection: "row-reverse", gap: 8 }, exportWord: { backgroundColor: "#2563eb", borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, flexDirection: "row", alignItems: "center", gap: 5 }, exportExcel: { backgroundColor: "#15803d", borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, flexDirection: "row", alignItems: "center", gap: 5 }, exportPrint: { backgroundColor: "#475569", borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, flexDirection: "row", alignItems: "center", gap: 5 }, filter: { borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, flexDirection: "row", alignItems: "center", gap: 5 }, filterActive: { backgroundColor: "#475569", borderColor: "#475569" }, filterText: { color: "#475569", fontSize: 12, fontWeight: "600" }, note: { backgroundColor: "#fffbeb", borderColor: "#fde68a", borderWidth: 1, borderRadius: 10, padding: 12, flexDirection: "row-reverse", gap: 8, alignItems: "flex-start" }, noteText: { flex: 1, color: "#92400e", fontSize: 12, lineHeight: 20, textAlign: "right" }, table: { backgroundColor: "white", borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 10, overflow: "hidden", minWidth: 760 }, tableHeader: { flexDirection: "row-reverse", backgroundColor: "#e2e8f0", borderBottomWidth: 1, borderColor: "#94a3b8" }, tableRow: { flexDirection: "row-reverse", borderBottomWidth: 1, borderColor: "#e2e8f0", minHeight: 48, alignItems: "center" }, lowRow: { backgroundColor: "#fff7ed" }, cell: { flex: 1, paddingHorizontal: 8, textAlign: "right", color: "#1e293b", fontSize: 12 }, headerCell: { fontWeight: "800", color: "#0f172a", paddingVertical: 10 }, empty: { textAlign: "center", color: "#64748b", padding: 40 }
});
