import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { MaterialIcons } from "@expo/vector-icons";
import { BackButton } from "@/components/back-button";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useLanguage } from "@/lib/language-context";
import { manufacturingStageService } from "@/lib/services/data.service";

const stageNames: Record<string, string> = { machines: "إنتاج المكائن", rosso: "الروسو", qalb: "القلب", kawiya: "الكاوية", inspection: "الفحص", packing: "التعبئة والتغليف", antislip: "مانع الانزلاق", storage: "التخزين" };

export default function OverdueCustodyReportScreen() {
  const colors = useColors();
  const { language } = useLanguage();
  const isAr = language === "ar";
  const [rows, setRows] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setRows(await manufacturingStageService.overdueCustodyReport()); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const groups = useMemo<any[]>(() => { const map = new Map<string, { worker: string; stage: string; count: number; pairs: number; rows: any[] }>(); rows.forEach((row) => { const key = `${row.workerName}|${row.stageName}`; const item = map.get(key) || { worker: row.workerName || "—", stage: row.stageName || "—", count: 0, pairs: 0, rows: [] as any[] }; item.count += 1; item.pairs += Number(row.quantityDozen || 0) * 12 + Number(row.quantityPair || 0); item.rows.push(row); map.set(key, item); }); return [...map.values()].sort((a, b) => b.pairs - a.pairs); }, [rows]);
  return <ScreenContainer style={{ backgroundColor: colors.background }}><View style={styles.header}><BackButton /><View style={styles.headerText}><Text style={styles.title}>{isAr ? "تقرير العهد المتأخرة" : "Overdue Custody Report"}</Text><Text style={styles.subtitle}>{isAr ? "حسب الموظف والمرحلة — التأخر يبدأ بعد 24 ساعة" : "By employee and stage — overdue after 24 hours"}</Text></View><MaterialIcons name="report-problem" size={28} color="#fff" /></View><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={() => void load()} />} contentContainerStyle={styles.content}><View style={styles.metrics}><View style={styles.metric}><Text style={styles.metricValue}>{rows.length}</Text><Text style={styles.metricLabel}>{isAr ? "عهدة متأخرة" : "Overdue items"}</Text></View><View style={styles.metric}><Text style={styles.metricValue}>{groups.length}</Text><Text style={styles.metricLabel}>{isAr ? "موظف / مرحلة" : "Employee / stage"}</Text></View><View style={styles.metric}><Text style={styles.metricValue}>{rows.reduce((sum: number, row: any) => sum + Number(row.quantityDozen || 0) * 12 + Number(row.quantityPair || 0), 0)}</Text><Text style={styles.metricLabel}>{isAr ? "إجمالي الأزواج" : "Total pairs"}</Text></View></View>{loading ? <ActivityIndicator color={colors.primary} size="large" /> : groups.length === 0 ? <View style={styles.empty}><MaterialIcons name="check-circle" size={44} color="#16a34a" /><Text style={styles.emptyTitle}>{isAr ? "لا توجد عهد متأخرة" : "No overdue custody"}</Text></View> : groups.map((group) => <View key={`${group.worker}-${group.stage}`} style={styles.group}><View style={styles.groupHeader}><Text style={styles.count}>{group.count} {isAr ? "عهدة" : "items"}</Text><View><Text style={styles.worker}>{group.worker}</Text><Text style={styles.stage}>{stageNames[group.stage] || group.stage} · {group.pairs} {isAr ? "زوج" : "pairs"}</Text></View></View>{group.rows.map((row: any) => <View key={String(row.id)} style={styles.row}><View style={styles.overdue}><Text style={styles.overdueText}>{row.hoursOpen} {isAr ? "ساعة" : "hours"}</Text></View><View style={styles.rowText}><Text style={styles.product}>{row.productName || "—"}</Text><Text style={styles.meta}>{Number(row.quantityDozen || 0)} {isAr ? "درزن" : "dozen"} + {Number(row.quantityPair || 0)} {isAr ? "زوج" : "pairs"} · {row.receivedAt ? new Date(row.receivedAt).toLocaleString(isAr ? "ar-SA" : "en-US") : "—"}</Text></View></View>)}</View>)}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ header: { backgroundColor: "#9a3412", padding: 14, flexDirection: "row", alignItems: "center", gap: 10 }, headerText: { flex: 1, alignItems: "flex-end" }, title: { color: "#fff", fontSize: 19, fontWeight: "900" }, subtitle: { color: "#ffedd5", fontSize: 11, marginTop: 3 }, content: { padding: 12, gap: 10, paddingBottom: 50 }, metrics: { flexDirection: "row-reverse", gap: 7 }, metric: { flex: 1, backgroundColor: "#fff7ed", borderWidth: 1, borderColor: "#fed7aa", borderRadius: 8, padding: 9, alignItems: "center" }, metricValue: { color: "#c2410c", fontSize: 18, fontWeight: "900" }, metricLabel: { color: "#9a3412", fontSize: 10, fontWeight: "800", textAlign: "center", marginTop: 3 }, group: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#fdba74", borderRadius: 10, overflow: "hidden" }, groupHeader: { backgroundColor: "#fff7ed", padding: 10, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, worker: { color: "#7c2d12", fontSize: 14, fontWeight: "900", textAlign: "right" }, stage: { color: "#c2410c", fontSize: 11, textAlign: "right", marginTop: 3 }, count: { color: "#fff", backgroundColor: "#ea580c", borderRadius: 5, paddingHorizontal: 7, paddingVertical: 5, fontSize: 10, fontWeight: "900" }, row: { padding: 9, borderTopWidth: 1, borderTopColor: "#fed7aa", flexDirection: "row", alignItems: "center", gap: 8 }, rowText: { flex: 1 }, product: { color: "#0f172a", fontWeight: "800", textAlign: "right" }, meta: { color: "#64748b", fontSize: 10, textAlign: "right", marginTop: 3 }, overdue: { backgroundColor: "#fee2e2", borderRadius: 4, padding: 5 }, overdueText: { color: "#b91c1c", fontSize: 10, fontWeight: "900" }, empty: { alignItems: "center", paddingVertical: 70, gap: 8 }, emptyTitle: { color: "#15803d", fontSize: 17, fontWeight: "900" } });
