import { useCallback, useEffect, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { MaterialIcons } from "@expo/vector-icons";
import { BackButton } from "@/components/back-button";
import { AttachmentPicker } from "@/components/attachment-picker";
import { SignaturePad } from "@/components/signature-pad";
import type { AttachmentFile } from "@/lib/services/attachment.service";
import { ScreenContainer } from "@/components/screen-container";
import { DateField } from "@/components/date-field";
import { useAuth } from "@/lib/auth-context";
import { productManufacturingRequestService } from "@/lib/services/api.service";
import { useRouter } from "expo-router";
const today = new Date().toISOString().slice(0, 10);
const statuses: Record<string, string> = { PENDING_SALES: "بانتظار اعتماد مدير التسويق والمبيعات", PENDING_PRODUCTION: "بانتظار مدير الإنتاج", RETURNED_TO_REP: "عاد للمندوب للتصحيح", RETURNED_TO_SALES: "عاد لمدير التسويق لمعالجة السبب", IN_PRODUCTION: "تم البدء بالإنتاج", PENDING_ADMIN: "محال للمدير العام", CLOSED_ADMIN: "مغلق حسب توجيهات المدير العام" };
export default function ProductManufacturingRequestScreen() {
  const { user } = useAuth(); const router = useRouter(); const [rows, setRows] = useState<any[]>([]); const [customerName, setCustomerName] = useState(""); const [productName, setProductName] = useState(""); const [productSize, setProductSize] = useState(""); const [productColor, setProductColor] = useState(""); const [quantityDozen, setQuantityDozen] = useState(""); const [orderDate, setOrderDate] = useState(today); const [deliveryDate, setDeliveryDate] = useState(""); const [notes, setNotes] = useState(""); const [attachments, setAttachments] = useState<AttachmentFile[]>([]); const [signature, setSignature] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const result = await productManufacturingRequestService.list(); setRows(Array.isArray(result) ? result : []); } catch (e) { console.error(e); } }, []); useEffect(() => { void load(); }, [load]);
  const save = async () => { if (!customerName.trim() || !productName.trim() || !quantityDozen || !deliveryDate) return Alert.alert("بيانات ناقصة", "أكمل العميل والصنف والكمية وموعد التسليم"); setBusy(true); try { await productManufacturingRequestService.create({ customerName: customerName.trim(), productName: productName.trim(), productSize: productSize.trim(), productColor: productColor.trim(), quantityDozen: Number(quantityDozen), orderDate, deliveryDate, attachments: attachments.map((file) => ({ name: file.name, url: file.uploadedUrl || file.uri, mimeType: file.mimeType })), signature: signature || `${user?.name || ""} — ${new Date().toISOString()}` }); setCustomerName(""); setProductName(""); setProductSize(""); setProductColor(""); setQuantityDozen(""); setDeliveryDate(""); setNotes(""); setAttachments([]); setSignature(""); await load(); Alert.alert("تم الحفظ", "تم رفع الطلب لمدير التسويق والمبيعات للاعتماد"); } catch (e: any) { Alert.alert("تعذر الحفظ", e?.message || "حدث خطأ"); } finally { setBusy(false); } };
  const decide = async (id: number, action: any) => { const notesValue = notes.trim() || (action === "sales_approve" ? "تم الاعتماد" : "تم تنفيذ الإجراء"); try { await productManufacturingRequestService.decide({ id, action, notes: notesValue, signature: `${user?.name || ""} — ${new Date().toISOString()}`, attachments: [] }); setNotes(""); await load(); Alert.alert("تم التنفيذ", "تم تسجيل القرار وإرسال الإشعار الرسمي"); } catch (e: any) { Alert.alert("تعذر تنفيذ القرار", e?.message || "لا تملك الصلاحية"); } };
  return <ScreenContainer style={{ backgroundColor: "#f8fafc" }}><View style={styles.header}><View><Text style={styles.title}>طلب تصنيع منتج</Text><Text style={styles.subtitle}>يفتح من الطلبات عند عدم توفر الصنف أو نقص الكمية</Text></View><BackButton /></View><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.card}><Text style={styles.section}>رفع طلب جديد</Text><View style={styles.grid}><Field label="اسم العميل *" value={customerName} set={setCustomerName} /><Field label="اسم المنتج *" value={productName} set={setProductName} /><Field label="المقاس" value={productSize} set={setProductSize} /><Field label="اللون" value={productColor} set={setProductColor} /><Field label="الكمية بالدرزن *" value={quantityDozen} set={setQuantityDozen} numeric /></View><View style={styles.dates}><DateField value={orderDate} onChange={setOrderDate} label="تاريخ الطلب" isAr /><DateField value={deliveryDate} onChange={setDeliveryDate} label="موعد التسليم *" isAr /></View><View style={styles.attachmentBox}><Text style={styles.label}>المرفقات (صورة أو ملف أو كاميرا)</Text><AttachmentPicker attachments={attachments} onAttachmentsChange={setAttachments} maxAttachments={5} /></View><SignaturePad label="التوقيع الإلكتروني لمقدم الطلب" onSave={setSignature} /><TouchableOpacity onPress={save} disabled={busy} style={styles.primary}><MaterialIcons name="send" size={18} color="white" /><Text style={styles.primaryText}>{busy ? "جارٍ الحفظ..." : "رفع الطلب للاعتماد"}</Text></TouchableOpacity></View>
    <View style={styles.card}><Text style={styles.section}>الطلبات وسير الاعتماد</Text><TextInput value={notes} onChangeText={setNotes} placeholder="ملاحظة القرار أو سبب الرفض أو الحل التصحيحي" style={[styles.input, { minHeight: 70 }]} multiline textAlign="right" />{rows.length === 0 ? <Text style={styles.empty}>لا توجد طلبات</Text> : rows.map((row) => <View key={row.id} style={styles.request}><View style={styles.requestTop}><Text style={styles.reference}>{row.referenceCode}</Text><Text style={styles.badge}>{statuses[row.status] || row.status}</Text></View><Text style={styles.requestText}>العميل: {row.customerName} — المنتج: {row.productName} — {row.quantityDozen} درزن</Text><Text style={styles.requestText}>الطلب: {row.orderDate} — التسليم: {row.deliveryDate} — مقدم الطلب: {row.requesterName}</Text><View style={styles.actions}>{(row.status === "PENDING_SALES" || row.status === "RETURNED_TO_SALES") && <><Action label="اعتماد التسويق" onPress={() => decide(row.id, "sales_approve")} color="#16a34a" /><Action label="رفض وإعادة للمندوب" onPress={() => decide(row.id, "sales_reject")} color="#dc2626" /></>}{row.status === "PENDING_PRODUCTION" && <><Action label="اعتماد الإنتاج" onPress={() => decide(row.id, "production_approve")} color="#16a34a" /><Action label="رفض مع السبب" onPress={() => decide(row.id, "production_reject")} color="#dc2626" /></>}{["RETURNED_TO_SALES", "PENDING_PRODUCTION"].includes(row.status) && <Action label="إحالة للمدير العام" onPress={() => decide(row.id, "escalate_admin")} color="#7c3aed" />}{row.status === "PENDING_ADMIN" && <Action label="إغلاق بتوجيه المدير العام" onPress={() => decide(row.id, "admin_close")} color="#0f766e" />}</View></View>)}</View>
  </ScrollView></ScreenContainer>;
}
function Field({ label, value, set, numeric = false }: { label: string; value: string; set: (v: string) => void; numeric?: boolean }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={set} keyboardType={numeric ? "numeric" : "default"} style={styles.input} textAlign="right" /></View>; }
function Action({ label, onPress, color }: { label: string; onPress: () => void; color: string }) { return <TouchableOpacity onPress={onPress} style={[styles.action, { backgroundColor: color }]}><Text style={styles.actionText}>{label}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ attachmentBox: { backgroundColor: "#f8fafc", borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 10, padding: 10, gap: 7 }, header: { backgroundColor: "#2563eb", padding: 18, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, title: { color: "white", fontSize: 20, fontWeight: "800", textAlign: "right" }, subtitle: { color: "#dbeafe", fontSize: 12, marginTop: 4, textAlign: "right" }, content: { padding: 16, gap: 14 }, card: { backgroundColor: "white", borderRadius: 14, borderWidth: 1, borderColor: "#e2e8f0", padding: 16, gap: 12 }, section: { fontSize: 16, fontWeight: "800", color: "#0f172a", textAlign: "right" }, grid: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 10 }, field: { flex: 1, minWidth: 220, gap: 5 }, label: { color: "#475569", fontWeight: "700", textAlign: "right", fontSize: 12 }, input: { minHeight: 42, borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 9, paddingHorizontal: 10, color: "#0f172a", backgroundColor: "#fff" }, dates: { flexDirection: "row-reverse", gap: 10 }, primary: { backgroundColor: "#2563eb", borderRadius: 10, minHeight: 46, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 7 }, primaryText: { color: "white", fontWeight: "800" }, empty: { color: "#64748b", textAlign: "center", padding: 20 }, request: { borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 10, padding: 12, gap: 8 }, requestTop: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, reference: { color: "#1d4ed8", fontWeight: "800" }, badge: { color: "#92400e", fontWeight: "700", fontSize: 12 }, requestText: { color: "#334155", textAlign: "right", fontSize: 13 }, actions: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 7 }, action: { borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8 }, actionText: { color: "white", fontSize: 12, fontWeight: "700" }
});
