import { useCallback, useEffect, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { MaterialIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { BackButton } from "@/components/back-button";
import { ScreenContainer } from "@/components/screen-container";
import { representativeService } from "@/lib/services/representative.service";
import { useColors } from "@/hooks/use-colors";

const LABELS: Record<string, string> = { PENDING_WAREHOUSE_ISSUE: "بانتظار التنفيذ", WAREHOUSE_PARTIAL: "تنفيذ جزئي / رد مطلوب", WAREHOUSE_EXECUTED: "تم التنفيذ", REPRESENTATIVE_CLOSED: "أغلقه المندوب" };
export default function WarehouseRepresentativeOrders() {
  const colors = useColors(); const router = useRouter(); const [rows, setRows] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [notes, setNotes] = useState<Record<number, string>>({});
  const load = useCallback(async () => { setLoading(true); try { const data: any = await representativeService.transactions.list({ transactionType: "order" }); setRows((data || []).filter((row: any) => ["PENDING_WAREHOUSE_ISSUE", "WAREHOUSE_PARTIAL", "WAREHOUSE_EXECUTED"].includes(row.status))); } catch (e: any) { Alert.alert("تعذر تحميل الطلبات", e?.message || "حدث خطأ"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const act = async (id: number, action: string) => { try { await representativeService.transactions.transition({ id, action, notes: notes[id] || "" }); setNotes((x) => ({ ...x, [id]: "" })); await load(); Alert.alert("تم الحفظ", action === "warehouse_execute" ? "تم تنفيذ الطلب واعتماده" : "تم تسجيل الملاحظة وإعادته للمندوب"); } catch (e: any) { Alert.alert("تعذر تنفيذ الإجراء", e?.message || "حدث خطأ"); } };
  return <ScreenContainer style={{ backgroundColor: colors.background }}><View style={styles.header}><BackButton /><View style={{ flex: 1 }}><Text style={styles.title}>طلبات المناديب</Text><Text style={styles.subtitle}>طلبات العملاء المحولة للمستودعات للإخراج والتنفيذ</Text></View><MaterialIcons name="assignment" size={26} color="#fff" /></View><ScrollView contentContainerStyle={styles.content}>{loading ? <Text style={styles.empty}>جارٍ تحميل الطلبات...</Text> : rows.length === 0 ? <Text style={styles.empty}>لا توجد طلبات بانتظار المستودع</Text> : rows.map((row) => <View key={row.id} style={styles.card}><View style={styles.cardHead}><Text style={styles.ref}>{row.referenceCode}</Text><Text style={styles.badge}>{LABELS[row.status] || row.status}</Text></View><Text style={styles.customer}>{row.customerName}</Text><Text style={styles.meta}>المندوب: {row.representativeName} · تاريخ الطلب: {row.orderDate || "-"} · موعد التسليم: {row.deliveryDate || "-"}</Text><View style={styles.items}>{(row.items || []).map((item: any, i: number) => <Text key={i} style={styles.item}>• {item.productName} — المقاس {item.size} — اللون {item.color} — {item.quantity} {item.quantityUnit === "dozen" ? "درزن" : "زوج"} — باركود {item.barcode || "-"}</Text>)}</View>{row.status !== "WAREHOUSE_EXECUTED" && <><TextInput value={notes[row.id] || ""} onChangeText={(v) => setNotes((x) => ({ ...x, [row.id]: v }))} placeholder="ملاحظات المستودع عند عدم التوفر أو التنفيذ الجزئي" multiline textAlign="right" style={styles.notes} /><View style={styles.actions}><TouchableOpacity style={styles.partial} onPress={() => void act(Number(row.id), "warehouse_partial")}><Text style={styles.actionText}>غير متاح / تنفيذ جزئي</Text></TouchableOpacity><TouchableOpacity style={styles.execute} onPress={() => void act(Number(row.id), "warehouse_execute")}><Text style={styles.actionText}>تم التنفيذ</Text></TouchableOpacity></View></>}{row.status === "WAREHOUSE_EXECUTED" && <Text style={styles.done}>تم تنفيذ الطلب — بانتظار إغلاق المندوب</Text>}<TouchableOpacity onPress={() => router.push({ pathname: "/representative-approvals", params: { id: String(row.id) } } as any)}><Text style={styles.detail}>عرض التفاصيل والسجل الزمني</Text></TouchableOpacity></View>)}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { backgroundColor: "#f59e0b", padding: 16, flexDirection: "row-reverse", alignItems: "center", gap: 12 }, title: { color: "#fff", fontWeight: "900", fontSize: 20, textAlign: "right" }, subtitle: { color: "#fffbeb", fontSize: 12, marginTop: 3, textAlign: "right" }, content: { padding: 16, gap: 12 }, card: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 12, padding: 14, gap: 8 }, cardHead: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, ref: { color: "#0f172a", fontWeight: "900" }, badge: { backgroundColor: "#fef3c7", color: "#92400e", paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, fontSize: 12, fontWeight: "800" }, customer: { fontSize: 17, fontWeight: "900", color: "#0f172a", textAlign: "right" }, meta: { color: "#64748b", fontSize: 12, textAlign: "right" }, items: { backgroundColor: "#f8fafc", padding: 10, gap: 4 }, item: { color: "#334155", fontSize: 12, textAlign: "right" }, notes: { minHeight: 54, borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 8, padding: 9, color: "#0f172a" }, actions: { flexDirection: "row-reverse", gap: 8 }, execute: { flex: 1, backgroundColor: "#15803d", padding: 11, borderRadius: 8, alignItems: "center" }, partial: { flex: 1, backgroundColor: "#dc2626", padding: 11, borderRadius: 8, alignItems: "center" }, actionText: { color: "#fff", fontWeight: "800", fontSize: 12 }, done: { color: "#15803d", fontWeight: "800", textAlign: "right" }, detail: { color: "#0369a1", fontWeight: "800", textAlign: "right", paddingTop: 4 }, empty: { textAlign: "center", color: "#64748b", padding: 40 } });
